-- AMBIORIX CRUZ ANGELES
-- JDBCBANK FOR PROJECT 0

-- DROPPING TABLES IF THEY ALREADY EXISTS
DROP TABLE TABLE_ACCOUNTS;
/

DROP TABLE TABLE_USERS;
/

-- CREATING NEW TABLES
CREATE TABLE TABLE_USERS (
    USER_ID NUMBER GENERATED AS IDENTITY, -- PRIMARY KEY
    USER_USERNAME VARCHAR2(20), -- USERNAME USED TO LOG IN
    USER_PASSWORD VARCHAR2(20), -- PASSWORD USED TO LOG IN
    USER_FIRSTNAME VARCHAR2(20), -- FIRST NAME
    USER_LASTNAME VARCHAR2(20) -- LAST NAME
);
/

CREATE TABLE TABLE_ACCOUNTS (
    ACCOUNT_ID NUMBER GENERATED AS IDENTITY, -- PRIMARY KEY
    ACCOUNT_NAME VARCHAR2(20), -- ACCOUNT NAME: EXAMPLE BANK NAME
    ACCOUNT_BALANCE NUMBER, -- BALANCE
    USER_ID NUMBER -- FOREIGN KEY TO TABLE_USERS
);
/

-- INSERTING SOME DUMMY DATA INTO TABLES
INSERT INTO TABLE_USERS(USER_USERNAME, USER_PASSWORD, USER_FIRSTNAME, USER_LASTNAME)
VALUES('REX13','REX', 'CRUZ', 'REXPASS');
/
INSERT INTO TABLE_USERS(USER_USERNAME, USER_PASSWORD, USER_FIRSTNAME, USER_LASTNAME)
VALUES('BILLY5','BILLY', 'SANCHES', 'MONEYBILLS');
/
INSERT INTO TABLE_USERS(USER_FIRSTNAME, USER_LASTNAME, USER_PASSWORD)
VALUES('REX', 'CRUZ', 'REXPASS');
/
INSERT INTO TABLE_USERS(USER_FIRSTNAME, USER_LASTNAME, USER_PASSWORD)
VALUES('REX', 'CRUZ', 'REXPASS');
/
INSERT INTO TABLE_USERS(USER_FIRSTNAME, USER_LASTNAME, USER_PASSWORD)
VALUES('REX', 'CRUZ', 'REXPASS');
/
INSERT INTO TABLE_USERS(USER_FIRSTNAME, USER_LASTNAME, USER_PASSWORD)
VALUES('REX', 'CRUZ', 'REXPASS');
/
INSERT INTO TABLE_USERS(USER_FIRSTNAME, USER_LASTNAME, USER_PASSWORD)
VALUES('REX', 'CRUZ', 'REXPASS');
/

INSERT INTO TABLE_ACCOUNTS(ACCOUNT_NAME, ACCOUNT_BALANCE, USER_ID)
VALUES('CHASE', 8676, );
/


